build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  amd64: ghcr.io/home-assistant/amd64-base:3.16
  armhf: ghcr.io/home-assistant/armhf-base:3.16
  armv7: ghcr.io/home-assistant/armv7-base:3.16
  i386: ghcr.io/home-assistant/i386-base:3.16
codenotary:
  base_image: notary@home-assistant.io
  signer: notary@home-assistant.io
args:
  BUILD_ARCH: ""
  BUILD_DATE: ""
  BUILD_DESCRIPTION: "ChromaDB vector database add-on"
  BUILD_NAME: "chromadb"
  BUILD_REF: ""
  BUILD_REPOSITORY: ""
  BUILD_VERSION: ""
labels:
  io.hass.type: "addon"
  org.opencontainers.image.title: "ChromaDB Add-on"
  org.opencontainers.image.description: "ChromaDB vector database add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/home-assistant-addons/addon-chromadb"
  org.opencontainers.image.licenses: "MIT"
