name: "ChromaDB"
version: "1.0.0"
slug: "chromadb"
description: "ChromaDB vector database add-on for Home Assistant"
url: "https://github.com/home-assistant-addons/addon-chromadb"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
init: false
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "ChromaDB API port"
ingress: true
ingress_port: 8000
panel_icon: "mdi:database"
webui: "http://[HOST]:[PORT:8000]"
options:
  log_level: "info"
  persistence: true
  data_path: "/data/chromadb"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  persistence: bool
  data_path: str
map:
  - share:rw
  - config:rw
